language: php

php:
  - 5.3
  - 5.4

before_script: composer install --dev --prefer-dist -q

script: bin/phpspec run -f pretty

notifications:
    irc: "irc.freenode.org#sylius-dev"
    email: travis-ci@sylius.org
