# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sales_order_list:
    pattern: /list
    defaults:
        _controller: sylius_sales.controller.order:indexAction
        _sortable: true
        _sorting:
            updatedAt: asc

sylius_sales_order_create:
    pattern: /create
    defaults:
        _controller: sylius_sales.controller.order:createAction

sylius_sales_order_update:
    pattern: /{id}/update
    defaults:
        _controller: sylius_sales.controller.order:updateAction

sylius_sales_order_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius_sales.controller.order:deleteAction

sylius_sales_order_show:
    pattern: /{id}
    defaults:
        _controller: sylius_sales.controller.order:showAction
